automerge: false
files:
  $actions/aws_s3.py:
    labels: aws_s3
  $callbacks/aws_resource_actions.py:
  $doc_fragments/aws.py:
  $doc_fragments/aws_credentials.py:
  $doc_fragments/aws_region.py:
  $doc_fragments/ec2.py:
  $inventories/aws_ec2.py:
    maintainers: $team_aws
    labels: aws_ec2
  $inventories/aws_rds.py:
  $lookups/:
    labels: aws cloud
  $module_utils/:
  $module_utils/ec2.py:
    labels: aws cloud ec2
  $modules/_aws_az_facts.py:
    authors: Sodki
  $modules/_aws_caller_facts.py:
    authors: orthanc sdubrul
  $modules/_cloudformation_facts.py:
    authors: jmenga waffie1
  $modules/_ec2_ami_facts.py:
    authors: prasadkatti
  $modules/_ec2_group_facts.py:
    authors: Sodki
  $modules/:
    authors: wimnat
    maintainers: $team_aws
    ignore: erydo nadirollo seiffert tedder
  $modules/_ec2_vpc_dhcp_option_facts.py:
    authors: naslanidis
  $modules/aws_az_info.py:
    authors: Sodki
  $modules/aws_caller_info.py:
    authors: orthanc sdubrul
  $modules/aws_s3.py:
    authors: lwade s-hertel
    maintainers: jillr tremble
  $modules/cloudformation.py:
    authors: jsmartin
    labels: cloudformation
  $modules/cloudformation_info.py:
    authors: jmenga waffie1
  $modules/ec2.py:
    authors: lwade skvidal tgerla
    labels: ec2
    ignore: erydo nadirollo seiffert skvidal
  $modules/ec2_ami.py:
    authors: Constantin07 gunzy83 scicoin-project wilvk
  $modules/ec2_ami_info.py:
    authors: prasadkatti
  $modules/ec2_elb_lb.py:
    authors: jsdalton
  $modules/ec2_group.py:
    authors: adq
    labels: ec2_group
  $modules/ec2_group_info.py:
    authors: Sodki
  $modules/ec2_key.py:
    authors: prasadkatti zbal
    labels: ec2_key
  $modules/ec2_metadata_facts.py:
    authors: roadmapper silviud
  $modules/ec2_snapshot.py:
    authors: willthames
  $modules/ec2_tag.py:
    authors: flowerysong lwade
    labels: ec2_tag
  $modules/ec2_tag_info.py:
    authors: tremble
    maintainers: jillr s-hertel
  $modules/ec2_vol.py:
    authors: lwade
    labels: ec2_vol
  $modules/ec2_vpc_dhcp_option.py:
    authors: joelthompson
  $modules/ec2_vpc_dhcp_option_info.py:
    authors: naslanidis
  $modules/ec2_vpc_net.py:
    authors: defionscode s-hertel
    maintainers: jillr tremble
    labels: ec2_vpc_net
    ignore: defionscode joshsouza ryansb simplesteph
  $modules/ec2_vpc_net_info.py:
    maintainers: $team_aws whiter
    labels: ec2_vpc_net_info
  $modules/ec2_vpc_subnet.py:
    authors: brandond erydo
macros:
  actions: plugins/action
  callbacks: plugins/callback
  doc_fragments: plugins/doc_fragments
  inventories: plugins/inventory
  lookups: plugins/lookup
  module_utils: plugins/module_utils
  modules: plugins/modules
  team_aws: jillr s-hertel tremble
