namespace: amazon
name: aws
version: 1.0.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: [amazon, aws, cloud]
dependencies:
  ansible.netcommon: '>=0.0.1'
repository: https://github.com/ansible-collections/amazon.aws
homepage: https://github.com/ansible-collections/amazon.aws
issues: https://github.com/ansible-collections/amazon.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
  - 'changelogs/.plugin-cache.yaml'
