namespace: community
name: aws
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  amazon.aws: '>=0.1.0'
repository: https://github.com/ansible-collections/community.aws.git
documentation: https://github.com/ansible-collections/community.aws/tree/master/docs
homepage: https://github.com/ansible-collections/community.aws
issues: https://github.com/ansible-collections/community.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
