---
namespace: amazon
name: aws
version: 5.5.3
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: A variety of Ansible content to help automate the management of AWS services.
license_file: COPYING
tags: [amazon, aws, cloud]
repository: https://github.com/ansible-collections/amazon.aws
documentation: https://ansible-collections.github.io/amazon.aws/branch/stable-5/collections/amazon/aws/index.html
homepage: https://github.com/ansible-collections/amazon.aws
issues: https://github.com/ansible-collections/amazon.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
  - 'changelogs/.plugin-cache.yaml'
