namespace: amazon
name: aws
version: 0.1.1
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  ansible.netcommon: '>=0.0.1'
repository: git@github.com:ansible-collections/amazon.aws.git
homepage: https://github.com/ansible-collections/amazon.aws
issues: https://github.com/ansible-collections/amazon.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
