namespace: amazon
name: aws
# the version key is generated during the release by Zuul
# https://github.com/ansible-network/releases/tree/master/ansible_releases/cmd
# A script based on https://pypi.org/project/pbr/ will generate the version
# key. The version value depends on the tag or the last git tag.
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: [amazon, aws, cloud]
dependencies:
  ansible.netcommon: '>=0.0.1'
repository: https://github.com/ansible-collections/amazon.aws.git
homepage: https://github.com/ansible-collections/amazon.aws
issues: https://github.com/ansible-collections/amazon.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
