major_changes:
- aws_config_rule - The module has been migrated from the ``community.aws`` collection.
  Playbooks using the Fully Qualified Collection Name for this module should be updated
  to use ``community.aws.aws_config_rule``.
- config_rule - The module has been migrated from the ``community.aws`` collection.
  Playbooks using the Fully Qualified Collection Name for this module should be updated
  to use ``community.aws.config_rule``.
