---
name: Run collection certification checks

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - stable-*
  workflow_dispatch:

concurrency:
  group: cert-ver-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@0b3575fff9a50e8057134e01862c52450648c3fc # v6.0.0
