---
name: Check Patchback Comment on Edit

on:
  issue_comment:
    types:
      - edited

jobs:
  check_patchback_comment:
    if: >
      github.event.issue.pull_request.merged == true &&
      test(github.event.comment.body, '💔 cherry-picking failed')
    runs-on: ubuntu-latest

    steps:
      - name: Add Label for Backport Failure
        run: |
          gh pr edit ${{ github.event.issue.number }} -R ${{ github.repository }} --add-label 'backport-failed'
