---
name: changelog and linters

on: [workflow_call] # allow this workflow to be called from other workflows

jobs:
  linters:
    uses: ansible-network/github_actions/.github/workflows/tox.yml@4678c74a7d712d55e663c88f66eec6d9c3642550 # @main as of 2026-09-21
    with:
      envname: ""
      labelname: lint
