---
name: update collection variables

concurrency:
  group: ${{ github.workflow }} @ ${{ github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - stable-*
  pull_request_target:
jobs:
  update-variables:
    uses: ansible-network/github_actions/.github/workflows/update_aws_variables.yml@446d4586bcde8bf6e1a9c085983bf172b59bd7b2 # @main as of 2026-03-25
